# /etc/apache2/conf-available/nwp.conf
Alias /nwp "/nwp"

<Directory /nwp>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted

    IndexOptions FancyIndexing
    DirectoryIndex index.html
</Directory>

# セキュリティ強化（任意だが推奨）
<FilesMatch "\.(htaccess|htpasswd|ini|php\~|bak)$">
    Require all denied
</FilesMatch>
